server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/asb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: asb
    password: asb

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: info

worker:
  consumer-name: worker-1
  group-name: sum-workers
  stream-key: stream:sum:jobs
  value-key: jobId

gemini:
  api-key: ${GEMINI_API_KEY:}

